# Generated by Django 2.2.1 on 2019-05-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('school', models.CharField(db_column='School', max_length=50)),
                ('city', models.CharField(db_column='City', max_length=20)),
                ('country', models.CharField(db_column='Country', max_length=20)),
                ('major', models.CharField(db_column='Major', max_length=50)),
                ('from_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('from_year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('current_school', models.BooleanField(default=False)),
                ('end_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('end_year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
            ],
            options={
                'db_table': 'School',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('techid', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('technology', models.CharField(max_length=20)),
                ('proficiency', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, max_length=10)),
                ('years', models.IntegerField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'db_table': 'Technology',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkPlaces',
            fields=[
                ('jobid', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('work_name', models.CharField(db_column='Work', max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('from_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('from_year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('current_job', models.BooleanField(default=False)),
                ('end_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('end_year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TechUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Technology')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.WorkPlaces')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectid', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='Project', max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.WorkPlaces')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
