# Generated by Django 2.2.1 on 2019-05-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190512_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True, 'verbose_name': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='techused',
            options={'managed': True, 'verbose_name': 'Tech Use', 'verbose_name_plural': 'Tech Uses'},
        ),
        migrations.AddField(
            model_name='workplaces',
            name='description',
            field=models.TextField(default='Enter job decription', max_length=200),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(default='Project Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='techused',
            name='purpose',
            field=models.TextField(default='Technology use', max_length=150),
        ),
    ]
