# Generated by Django 2.2.1 on 2019-05-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190512_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplaces',
            name='work_name',
            field=models.CharField(db_column='Company', max_length=20, verbose_name='Company'),
        ),
    ]
