# Generated by Django 2.2.1 on 2019-05-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190512_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplaces',
            name='work_name',
            field=models.CharField(db_column='Company', max_length=50, verbose_name='Company'),
        ),
    ]
