# Generated by Django 2.2.1 on 2019-05-13 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190512_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Framework', 'Framework'), ('Cloud Services', 'Cloud Services'), ('Software', 'Software'), ('Operating System', 'Operating System')], default='Programming', max_length=20),
        ),
        migrations.AlterField(
            model_name='techused',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Projects'),
        ),
    ]
