# Generated by Django 2.2.1 on 2019-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190512_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, db_column='State', max_length=10),
        ),
        migrations.AddField(
            model_name='workplaces',
            name='state',
            field=models.CharField(blank=True, db_column='State', max_length=10),
        ),
    ]
