# Generated by Django 2.2.1 on 2019-05-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190513_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
