# Generated by Django 2.2.1 on 2019-05-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190513_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='techused',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Technology'),
        ),
    ]
