# Generated by Django 2.2.1 on 2019-05-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190514_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='degree',
            field=models.CharField(db_column='Degree', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='major',
            field=models.CharField(db_column='Major', max_length=20),
        ),
    ]
