# Generated by Django 2.2.1 on 2019-05-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190514_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.WorkPlaces'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='degree',
            field=models.CharField(db_column='Degree', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Projects'),
        ),
        migrations.AlterField(
            model_name='task',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.WorkPlaces'),
        ),
        migrations.AlterField(
            model_name='techused',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
        migrations.AlterField(
            model_name='techused',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.WorkPlaces'),
        ),
    ]
