# Generated by Django 2.2.1 on 2019-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190514_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='FirstName', max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='LastName', max_length=20, verbose_name='Last Name')),
                ('occupation', models.CharField(max_length=20)),
                ('bio', models.TextField(default='Bio', max_length=600)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
