# Generated by Django 2.2.1 on 2019-05-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cell_number',
            field=models.BigIntegerField(db_column='CellNumber', default=9547935283, verbose_name='Cell Number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='kevinnjeri@live.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(db_column='FirstName', default='Kevin', max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(db_column='LastName', default='Anderson', max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='Software Developer', max_length=20),
        ),
    ]
