# Generated by Django 2.2.1 on 2019-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190515_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='proficiency',
            field=models.IntegerField(choices=[(0, 0), (1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60), (7, 70), (8, 80), (9, 90)], default=1),
        ),
    ]
