# Generated by Django 2.2.1 on 2019-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190517_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='proficiency',
            field=models.IntegerField(choices=[(0, 0), (10, 1), (20, 2), (30, 3), (40, 4), (50, 5), (60, 6), (70, 7), (80, 8), (90, 9)], default=1),
        ),
    ]
