# Generated by Django 2.2.1 on 2019-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190517_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='proficiency',
            field=models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=1),
        ),
    ]
