# Generated by Django 2.2.1 on 2019-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_workplaces_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=26, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='email2',
            field=models.EmailField(default='devkevengineer@gmail.com', max_length=30),
        ),
    ]
