# Generated by Django 2.2.1 on 2019-05-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190520_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='kevinnjeri@live.com', max_length=30),
        ),
    ]
