# Generated by Django 2.2.1 on 2019-05-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190520_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techused',
            name='school',
        ),
        migrations.RemoveField(
            model_name='techused',
            name='work',
        ),
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('iOS Development', 'iOS Development'), ('Desktop Development', 'Desktop Development')], max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techused',
            name='purpose',
            field=models.CharField(default='Technology use', max_length=300),
        ),
    ]
