# Generated by Django 3.0.1 on 2019-12-29 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='FirstName', default='Kevin', max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='LastName', default='Anderson', max_length=20, verbose_name='Last Name')),
                ('occupation', models.CharField(default='Software Developer', max_length=20)),
                ('email', models.EmailField(default='kevinnjeri@live.com', max_length=30)),
                ('email2', models.EmailField(default='devkevengineer@gmail.com', max_length=30)),
                ('age', models.IntegerField(default=26)),
                ('bio', models.TextField(default='Bio', max_length=600)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_column='Project', max_length=30)),
                ('link', models.URLField(blank=True, max_length=128, verbose_name='Url')),
                ('personal', models.BooleanField(default=False)),
                ('description', models.TextField(default='Project Description', max_length=600)),
            ],
            options={
                'verbose_name': 'Project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_column='Type', max_length=60)),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(db_column='School', max_length=50)),
                ('city', models.CharField(db_column='City', max_length=20)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10)),
                ('country', models.CharField(db_column='Country', max_length=20)),
                ('degree', models.CharField(db_column='Degree', max_length=50, null=True)),
                ('concentration', models.CharField(db_column='Concentration', max_length=20)),
                ('from_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('from_year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('current_school', models.BooleanField(default=False)),
                ('end_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('end_year', models.IntegerField(blank=True, choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True)),
            ],
            options={
                'db_table': 'School',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Framework', 'Framework'), ('Cloud Services', 'Cloud Services'), ('Software', 'Software'), ('Operating System', 'Operating System')], default='Programming', max_length=20)),
                ('technology', models.CharField(max_length=20)),
                ('proficiency', models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=1)),
                ('years', models.DecimalField(decimal_places=1, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'db_table': 'Technology',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(db_column='Company', max_length=50, verbose_name='Company')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, max_length=128, verbose_name='Url')),
                ('from_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('from_year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)])),
                ('current_job', models.BooleanField(default=False)),
                ('end_month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('end_year', models.IntegerField(blank=True, choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True)),
                ('description', models.TextField(default='Enter job description', max_length=600)),
                ('extra', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TechUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(default='Technology use', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Projects')),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Technology')),
            ],
            options={
                'verbose_name': 'Tech Use',
                'verbose_name_plural': 'Tech Uses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=800)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Projects')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.WorkPlaces'),
        ),
        migrations.AddField(
            model_name='projects',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.School'),
        ),
    ]
