# Generated by Django 3.0.1 on 2019-12-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=50, verbose_name='Type')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('cert_number', models.CharField(max_length=20, verbose_name='Certificate Number')),
                ('source', models.CharField(max_length=30, verbose_name='Provider')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
