# Generated by Django 3.0.1 on 2020-01-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20191231_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='cert_type',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='certification',
            name='cert_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10, null=True, verbose_name='Certificate Month'),
        ),
        migrations.AddField(
            model_name='certification',
            name='cert_year',
            field=models.CharField(blank=True, choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], max_length=10, null=True, verbose_name='Certificate Year'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Projects'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Technology'),
        ),
        migrations.AlterField(
            model_name='school',
            name='end_year',
            field=models.IntegerField(blank=True, choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='from_year',
            field=models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)]),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Framework', 'Framework'), ('Cloud Services', 'Cloud Services'), ('Software', 'Software'), ('Operating System', 'Operating System'), ('Application Type', 'Application Type')], default='Programming', max_length=20),
        ),
        migrations.AlterField(
            model_name='workplaces',
            name='end_year',
            field=models.IntegerField(blank=True, choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], null=True),
        ),
        migrations.AlterField(
            model_name='workplaces',
            name='from_year',
            field=models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)]),
        ),
    ]
